spring:
  datasource:
    url: jdbc:postgresql://localhost/search
    username: postgres
    password: hojats2878
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none


locker:
  authorization-enable: true
  locker-count: 10