spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: HameShakha
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

locker:
  authorization-enable: true
  locker-count: 10